### ISSUE TITLE
Questions on the choice of  "nconf" "cutoff" Tags

### ISSUE THREAD

**Issue by WhfQiu** [vanroeke/qscaild#1]
Question closed

**Comment by vanroeke** [comment]
Dear user,

Thank you for your feedback, here are some answers to your questions:

1) nconf is the total number of displaced supercells created. So the total number of forces computed at each cycle is nconf x number of atoms in a supercell x 3.

2) cutoff is used solely for third order force constants, as an input to the thirdorder script https://bitbucket.org/sousaw/thirdorder/src/master/
Please see a clearer description of this parameter on the above repository.

Best regards,
Ambroise

**Comment by WhfQiu** [comment]
Dear Dr. Ambroise,

Thank you very much for your prompt response. Now I understand it more clearly. 
But I still have a few questions and would like to hear your suggestions.

Regarding the free energy: I see there is out_convergence results of force constants, but how about the convergence of free energy ? 
How could I extract the free energy at a given temperature? Should this be done by Phonopy?

Thank you very much for your patience and attention.

Best regards,
Anonymous user
