### ISSUE TITLE
Question of Free Energy Calculation

### ISSUE THREAD

**Issue by WhfQiu** [vanroeke/qscaild#2]
Question closed

**Comment by vanroeke** [comment]
On this matter, please read Section 2.3 of the QSCAILD paper https://doi.org/10.1016/j.cpc.2021.107945 and references therein. You can make good use of phonopy indeed, at least for the entropic term.

**Comment by WhfQiu** [comment]
Thank you very much for your suggestion.

**Comment by WhfQiu** [comment]
Dear Dr. Ambroise,

There are 4 kinds of “number of irreducible elements” in out_sym file.
But I am a bit confused.

So, my question is: which one shall I refer to to  set  nconf value in “parameters” ? Is it the “3rd order number …… after acoustic sum rules” ? or the max or min of them?  (in case I already set symm_acoustic = True)

Thank you very much for your kind attention and support.



Best regards,

Haifa QIU

[https://www.polyu.edu.hk/emaildisclaimer/85A-PolyU_Email_Signature.jpg]

Disclaimer:

This message (including any attachments) contains confidential information intended for a specific individual and purpose. If you are not the intended recipient, you should delete this message and notify the sender and The Hong Kong Polytechnic University (the University) immediately. Any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited and may be unlawful.

The University specifically denies any responsibility for the accuracy or quality of information obtained through University E-mail Facilities. Any views and opinions expressed are only those of the author(s) and do not necessarily represent those of the University and the University accepts no liability whatsoever for any losses or damages incurred or caused to any party as a result of the use of such information.
